name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CQServerDeclare
    steps:
      - name: SetDocker
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: docker build -t qinbatista/cq_qinyupeng_com_client_debian .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker
        run: docker push qinbatista/cq_qinyupeng_com_client_debian
